name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: Features
    labels: [feat, feature, enhancement]
  - title: Fixes
    labels: [fix, bug]
  - title: Docs
    labels: [docs]
  - title: CI
    labels: [ci, chore]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changes
  $CHANGES
